import express from 'express';
import cors from 'cors';
import bodyParser from 'body-parser';
import auth from './routes/auth.js';
import shipments from './routes/shipments.js';
import payments from './routes/payments.js';
import ai from './routes/ai.js';
import faqs from './routes/faqs.js';
import tickets from './routes/tickets.js';
import admin from './routes/admin.js';
const app = express();
app.use(cors()); app.use(bodyParser.json());
app.use('/api/auth', auth);
app.use('/api/shipments', shipments);
app.use('/api/payments', payments);
app.use('/api/ai', ai);
app.use('/api/faqs', faqs);
app.use('/api/tickets', tickets);
app.use('/api/admin', admin);
const port = process.env.PORT || 4000;
app.listen(port, ()=> console.log('TrackAS backend running on', port));
